[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]

tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
dotenvy = "0.15"
validator = { version = "0.18", features = ["derive"] }



# The Don Framework
don_core = "0.3.0"
don_macros = "0.3.0"